<?php
declare(strict_types=1);
require __DIR__ . '/lib.php';
portal_start_session();
if (!portal_is_authenticated()) { header('Location: /'); exit; }
$config = portal_config();
$path = __DIR__ . '/storage/daily-log.json';
$days = is_file($path) ? json_decode((string) file_get_contents($path), true) : [];
if (!is_array($days)) $days = [];
$kindCounts=[];$productCounts=[];$totalMinutes=0;
foreach($days as $day){foreach(($day['entries']??[]) as $e){$kind=$e['kind']??'other';$product=$e['product']??'Other';$kindCounts[$kind]=($kindCounts[$kind]??0)+1;$productCounts[$product]=($productCounts[$product]??0)+1;$totalMinutes+=(int)($e['minutes']??0);}}
arsort($kindCounts); arsort($productCounts);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Daily Log — Built by LT</title><link rel="stylesheet" href="/app.css?v=6"><style>
.log-shell{max-width:1240px;margin:auto;padding:28px 24px 80px}.log-nav{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid;padding-bottom:16px}.log-nav a{text-decoration:none;color:inherit}.log-tabs{display:flex;gap:6px}.log-tabs a{padding:8px 12px;border:1px solid #bbb;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.log-tabs .active{background:#111;color:#fff}.log-hero{display:grid;grid-template-columns:1fr auto;gap:30px;padding:38px 0 24px}.log-hero h1{font-size:clamp(38px,6vw,70px);line-height:.9;margin:0}.log-hero p{max-width:520px}.rollup{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid;margin:0 0 30px}.rollup div{padding:14px 16px;border-right:1px solid}.rollup div:last-child{border:0}.rollup strong{display:block;font-size:26px}.rollup span{font-size:11px;text-transform:uppercase;letter-spacing:.08em}.day{border-top:2px solid;margin-top:30px}.day-head{display:flex;justify-content:space-between;align-items:baseline;padding:15px 0}.day-head h2{margin:0;font-size:24px}.day-head span{font-size:12px;text-transform:uppercase}.log-table{width:100%;border-collapse:collapse;font-size:13px}.log-table th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:.08em;padding:8px;border-bottom:1px solid #aaa}.log-table td{padding:10px 8px;border-bottom:1px solid #ddd;vertical-align:top}.pill{display:inline-block;border:1px solid;padding:3px 6px;font-size:10px;text-transform:uppercase}.prio{font-weight:700}.next{color:#555;max-width:310px}.minutes{white-space:nowrap}.tomorrow{margin-top:14px;padding:12px 14px;background:#111;color:#fff;font-size:13px}.analytics-preview{margin-top:42px;border-top:1px solid;padding-top:20px}.mini-bars{display:flex;gap:8px;flex-wrap:wrap}.mini-bars span{border:1px solid;padding:7px 9px;font-size:11px}.muted{opacity:.55}@media(max-width:800px){.log-hero{grid-template-columns:1fr}.rollup{grid-template-columns:1fr}.rollup div{border-right:0;border-bottom:1px solid}.log-table th:nth-child(4),.log-table td:nth-child(4),.log-table th:nth-child(6),.log-table td:nth-child(6){display:none}.log-shell{padding:18px 12px 60px}}
</style></head><body><div class="log-shell"><nav class="log-nav"><a class="brand" href="/"><span>BUILT</span><i>by</i><span>LT</span></a><div class="log-tabs"><a href="/">Dashboard</a><a class="active" href="/log.php">Daily log</a></div></nav><header class="log-hero"><div><p class="eyebrow">Founder record / day by day</p><h1>Daily<br><em>log.</em></h1></div><p>Compact record of what shipped, what broke, what was learned and what consumed time. The data model already includes optional minutes so time allocation can roll into the dashboard later.</p></header><section class="rollup"><div><span>Logged actions</span><strong><?= array_sum($kindCounts) ?></strong></div><div><span>Days recorded</span><strong><?= count($days) ?></strong></div><div><span>Time tracked</span><strong><?= $totalMinutes ? round($totalMinutes/60,1).'h' : '—' ?></strong><small class="muted"> starts when minutes are logged</small></div></section><?php foreach($days as $day): ?><section class="day"><div class="day-head"><h2><?= htmlspecialchars((new DateTimeImmutable($day['date']))->format('D · M j, Y')) ?></h2><span><?= count($day['entries']??[]) ?> entries</span></div><table class="log-table"><thead><tr><th>Product</th><th>Type</th><th>What happened</th><th>Impact</th><th>Priority</th><th>Next</th><th>Time</th></tr></thead><tbody><?php foreach(($day['entries']??[]) as $e): ?><tr><td><strong><?= htmlspecialchars($e['product']??'—') ?></strong></td><td><span class="pill"><?= htmlspecialchars($e['kind']??'—') ?></span></td><td><?= htmlspecialchars($e['title']??'') ?></td><td><?= htmlspecialchars($e['impact']??'—') ?></td><td class="prio"><?= htmlspecialchars($e['priority']??'—') ?></td><td class="next"><?= htmlspecialchars($e['next']??'—') ?></td><td class="minutes"><?= isset($e['minutes'])&&$e['minutes']!==null ? (int)$e['minutes'].'m' : '—' ?></td></tr><?php endforeach; ?></tbody></table><?php if(!empty($day['tomorrow_target'])): ?><div class="tomorrow"><strong>Tomorrow →</strong> <?= htmlspecialchars($day['tomorrow_target']) ?></div><?php endif; ?></section><?php endforeach; ?><section class="analytics-preview"><p class="eyebrow">Rollup-ready</p><h2>Task mix</h2><div class="mini-bars"><?php foreach($kindCounts as $kind=>$count): ?><span><?= htmlspecialchars($kind) ?> · <strong><?= $count ?></strong></span><?php endforeach; ?></div><p class="muted">As days accumulate, this becomes task volume by type, product and eventually hours spent vs. outcomes.</p></section></div></body></html>